name: Release and Publish to NPM
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
      - name: Install dependencies and build 🔧
        run: pnpm i --frozen-lockfile
      - name: Initialize PNPM config
        run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Build
        run: pnpm build
      - name: Run release
        run: pnpm run release --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: End message
        run: echo 'Job done'
